name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build
      run: '& "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" SuperLauncher.sln /build release'
