name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: '& "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" SuperLauncher.sln /build release'
      
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        path: .\SuperLauncherInstaller\Release\SuperLauncherInstaller.msi
        retention-days: 90
